//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxmetshinLS
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Resources;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }

        public string BithdayStr
        {
            get
            {
                if (this.Birthday != null)
                {
                    return this.Birthday.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }

        public string StarTime
        {
            get
            {
                var entryList = ClientService
                    .Where(x => x.ClientID == this.ID)
                    .OrderByDescending(x => x.StartTime)
                    .ToList();
                if(entryList.Any())
                {
                    return entryList.First().StartTime.ToShortDateString();
                }
                else
                {
                    return "нет";
                }
            }
        }
        public string RegistrationDateString
        {
            get
            {
                if(this.RegistrationDate != null)
                {
                    return RegistrationDate.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }

        public string GenderStr
        {
            get
            {
                if(GenderCode == "1")
                {
                    return "мужской";
                }
                else
                {
                    return "женский";
                }
            }
        }
        public string FIO
        {
            get
            {
                return this.FirstName + " " + this.LastName + " " + Patronymic;
            }
        }
        public int VisitCount
        {
            get
            {
                var datelist = ClientService.Where(p=> p.ClientID == this.ID).ToList();
                return datelist.Count;
            }
        }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
